### ISSUE TITLE
'monetizationstart' doesn't fire when switching tabs quickly

### ISSUE THREAD

**Issue by sentientwaffle** [coilhq/web-monetization-projects#105]
To reproduce (while logging monetization events):

1. Load a monetized page. Wait for payments to start. The `monetizationstart` event fires.
2. Switch to another (non-monetized) tab. The payments stop. Quickly switch back to the first tab.
3. The payments restart. In the page console logs, there is a `monetizationstop` event from switching off to the other tab. There is no second `monetizationstart` event from the payments restarting.

If you go through the steps with a longer pause on the non-monetized tab, things behave as expected --  the second `monetizationstart` event fires.

cc: @sublimator

**Comment by sublimator** [comment]
Hrmmm, I have an idea about what it could be. Probably a regression introduced in #90  circa packetNumber reset

**Comment by sublimator** [comment]
This still seems to be a problem if you frantically switch between a monetized and non-monetized tab as fast as you can hit the keys, land on the non-monetized page, then return to the monetized one. The start event doesn't fire. It gets jammed on pending

**Comment by sublimator** [comment]
Haven't seen this when going through checklist for the last couple of releases
