### ISSUE TITLE
[SAFARI] MacOS Icon 

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#1088]
- [x] Added temporary hack, exported res/CoilLogo.svg using https://svgtopng.com/ 
- [x] Get Fab/Oscar input
  - Will likely be shown in the App Store when people are looking for extensions

Need, at minimum, 512x512 and 1024x1024 (512@2x)

![image](https://user-images.githubusercontent.com/525211/93872582-903a8800-fcfa-11ea-8202-48aac2a1b187.png)
![image](https://user-images.githubusercontent.com/525211/93872614-97fa2c80-fcfa-11ea-98d6-3f6ea7db456a.png)

**Comment by fruehle** [comment]
[Archive.zip](https://github.com/coilhq/web-monetization-projects/files/5276680/Archive.zip)
Hi Nic, here are some logo version for the specs above. I think you probably should use the square ones.
I just added the circular option just in case.

**Comment by sublimator** [comment]
Thanks!

**Comment by sublimator** [comment]
Closed with #1109
