### ISSUE TITLE
Tipping button appears inconsistently

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#1093]
User reported:
> Hmm, sometimes my extension forgets that I'm part of the tipping pilot. The other day, I disabled the extension and then I re-enabled it just now and it doesn't show the tipping button (but WM appears to work)

Response:
> How often have you seen this?
When you say "WM appears to work"  could it be that the stream was only setting up and not actually paying yet? Because I believe tipping using something from the open stream ( exchange rates ? ) and so will not show the button until it has this information.
Perhaps it would be better to simply disable it (perhaps with a tooltip), rather than hide it completely ?

User Response:
> Gotcha. Yeah, at a minimum that seems like it would help us narrow down the issue.
I'm not sure what state the steam was in exactly. I can only tell you that it was doing the animation with the green dots and saying that it was paying.
(If it shows that animation without having actually successfully paid anything that could be a bit problematic in its own right because we'd be incorrectly telling the user that we're paying when we actually aren't yet. More of a question for Fabi though as to what the experience should be during different stages of initialization.)

Relevant code:
https://github.com/coilhq/web-monetization-projects/blob/e74ededf74487bd568e7f6b01339c820c6f27415/packages/coil-extension/src/popup/components/TipButton.tsx#L42-L61

**Comment by fruehle** [comment]
I’m probably not much help for this issue.
Assigned it to Ben :)

**Comment by sublimator** [comment]
@fruehle 
> More of a question for Fabi though as to what the experience should be during different stages of initialization

Don't let the code snippet put you off!
I think Stef wanted your input for the UX :)

**Comment by fruehle** [comment]
So, if I understand correctly you don't have an initializing state for the extension but instead show the animated svg (which suggests streaming payments)?
A simple fix would be to show the animation only when you are actually paying. If the initializing state takes a while I can provide you a different animation for the initializing state. (I'm thinking maybe just animate the little grey dots back and forth)

@sublimator let me know if I understand the issue correctly.

**Comment by sublimator** [comment]
@fruehle 

Yep, you got it!
> (I'm thinking maybe just animate the little grey dots back and forth)

Sounds good to me

**Comment by sublimator** [comment]
#1110

**Comment by fruehle** [comment]
[stream_connect.svg.zip](https://github.com/coilhq/web-monetization-projects/files/5294433/stream_connect.svg.zip)
Here is a simple bounce animation for the grey dots, let me know if that works.

**Comment by sharafian** [comment]
Have we determined why the tip button isn't showing up? The animation on the streaming payments seems to be a sub-issue here

**Comment by sublimator** [comment]
@sharafian 

The tipping button was hidden until the stream started, due to requirements to get an exchange rate. 

I changed it to just disable it, instead of hiding it.

Perhaps the OP had a particularly long connection phase, during which the animation was showing ( it was showing on localStorage updates to monetizedTotal, but not filtering out zeros (fixed in #1110 )) and the tipping button was hidden.
