### ISSUE TITLE
Change polyfill to use document.dispatchEvent(...) rather than window.postMessage(...)

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#1436]
Coordinate with @wmurphyrd
WICG/webmonetization#137

**Comment by sublimator** [comment]
Coordinate with @wmurphyrd 
https://github.com/WICG/webmonetization/issues/137

**Comment by wmurphyrd** [comment]
@sublimator does the closed issue mean this change will not be going in?

**Comment by sublimator** [comment]
@wmurphyrd 

Sorry, it made it's way in to 0.0.52 which will be published hopefully next week! 


```
- Reduce <script> injected code to just one [#1254](https://github.com/coilhq/web-monetization-projects/pull/1254) [#1503](https://github.com/coilhq/web-monetization-projects/pull/1503)
- Remove 'unsafe-eval' from CSP in favor of sha256 of singular polyfill [#1542](https://github.com/coilhq/web-monetization-projects/pull/1542)
```

**Comment by wmurphyrd** [comment]
Thanks @sublimator! Does #1542 mean CSP pages will allow the polyfill injection and the separate polyfill will longer be required?

**Comment by sublimator** [comment]
@wmurphyrd 

No, depending on the page's CSP policy ( which seems to take precedence ) you may still need to include the polyfill.
The main benefit is that it's easier for add-ons to get reviewed/published. The Mozilla/FF add-ons store recently questioned our use of 'unsafe-eval' so we responded by removing it and simply listing the hash of the polyfill.

Thanks.

**Comment by wmurphyrd** [comment]
@sublimator awesome thanks for explaining. New version of `web-monetization-polyfill` is published
