### ISSUE TITLE
Possibility to trigger web monetization payment request from UI elements?

### ISSUE THREAD

**Issue by blackforestboi** [coilhq/web-monetization-projects#1525]
Hey folks! 

I couldn't find anything in the API docs that gave me a conclusive answer to this:
Is it possible to trigger the payment request from a UI element like this one?

We'd like to enable users to click on the "support creator button" in our own UI to send off a payment request. 

![Screenshot 2021-02-01 at 14 22 27](https://user-images.githubusercontent.com/7870039/106464440-f00b2180-6498-11eb-80a6-a2cfa1fb57a3.png)

Thanks!

**Comment by drsm79** [comment]
Can't you do this by having the button click change/add/remove the ILP pointer?

**Comment by blackforestboi** [comment]
But would the user then have to press again on the wallet payment button? E.g when using Coil. 

Ideally the user only has to click once and later even not at all because its automated. So a programmatic payment request would be great. 

So do i have to assume thats not working?
If not any plans that this is supported in the future?

**Comment by blackforestboi** [comment]
Ok rereading the specs again gave me some clue that your suggestion may work! (?)

“If your site is adding a meta tag dynamically, then the state begins in stopped. It transitions to pending after the tag is added.”
