### ISSUE TITLE
Triggers errors on pages with SVG objects

### ISSUE THREAD

**Issue by da2x** [coilhq/web-monetization-projects#1640]
My console gets filled up with one–four copies of this error whenever the Coil extension is enabled on any website with an `<object data="some.svg" type="image/svg+xml"></object>` ([example page](https://css-tricks.com/lodge/svg/08-using-svg-iframeobjectembed/)). 

```
XML Parsing Error: not well-formed
Location: 
Line Number 5, Column 38:
```

See [this note](https://docs.w3cub.com/dom/xmlhttprequest/overridemimetype#Example).

Firefox 86, macOS/Linux/Windows. Coil 0.0.51-amo.

**Comment by sublimator** [comment]
Thanks for the report! Will look into it

**Comment by sublimator** [comment]
Related #1642
