### ISSUE TITLE
Update popup copy 

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#1724]
![image](https://user-images.githubusercontent.com/19295116/111818690-d6d9fb00-88b5-11eb-80ee-5d9aeac377f3.png)

**Comment by sublimator** [comment]
@fruehle 

Do you have a vector for the `$-<|` icon ?

**Comment by sublimator** [comment]
Ok, I found one here: 
https://webmonetization.org/img/wm-icon.svg

**Comment by fruehle** [comment]
[wm-icon.zip](https://github.com/coilhq/web-monetization-projects/files/6183100/wm-icon.zip)
Please, use this icon, thank you :)

**Comment by sublimator** [comment]
haha, NOW you send me, after I already lovingly got my color selector out ?? 

cheers!
