### ISSUE TITLE
setCoilUrlForPopupIfNeeded loop

### ISSUE THREAD

**Issue by sentientwaffle** [coilhq/web-monetization-projects#186]
Sometimes (but not always) when I open chrome, the extension gets stuck in an infinite loop of printing:

```
BackgroundScript.ts:295  coil-extension:background:BackgroundScript  setting coil url for popup https://coil.com/
BackgroundScript.ts:380  coil-extension:background:BackgroundScript  reloadTabState from= setCoilUrlForPopupIfNeeded {
  "lastMonetization": {
    "command": null,
    "timeMs": 1576174480615
  },
  "playState": "playing",
  "monetized": false,
  "adapted": false,
  "total": 0,
  "stickyState": "auto",
  "icon": {
    "path": "../res/icn-coil-off.png"
  },
  "badge": {
    "text": ""
  }
}
```

very rapidly, to the point where the background page is using 100% of a core. If I cycle through my tabs it eventually stops (I'm not sure what the actual condition to end it is). I'm using `@coil/extension@0.0.42`, pointed at staging.

**Comment by sublimator** [comment]
Wonder if related to #203

**Comment by sentientwaffle** [comment]
:+1: it does look like #203 might have the same underlying issue.

**Comment by sublimator** [comment]
@sentientwaffle 
Have you seen this much more ?

**Comment by sentientwaffle** [comment]
No, I haven't seen it recently.
