### ISSUE TITLE
Refresh token periodically such that the token always has 27-28 days validity

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#1917]
If you don't visit coil.com or monetized sites frequently enough, you won't get a refreshed token. While the extension DOES refresh tokens, because it (foolishly, it seems) tries not to refresh too often, a short window is created, where if you don't trigger a refresh in that period (by visiting a monetized site) then the token will expire. The fix would be to more eagerly refresh, triggered on an interval, not just by visiting a monetized site.

**Comment by traviscrist** [comment]
@sublimator whats the current interval used for this? It sounds like making this more eager as you suggested may be a way to fix this.

**Comment by sublimator** [comment]
There's currently no interval and I don't think there ever was one.

**Comment by sublimator** [comment]
I assumed before it was a regression I did when aggressively refactoring, but looking at the old code it seems the logic is much the same: https://github.com/coilhq/coil-extension/blob/9d87e3d4fa5a20b5e98fbd019aa852f00f65a35c/src/background.ts#L348-L353
