### ISSUE TITLE
Setup CI held job to publish `web-monetization-types` to npm

### ISSUE THREAD

**Issue by sidvishnoi** [coilhq/web-monetization-projects#1960]
I would be nice if WebMonetization projects outside this repo could make use of types from https://github.com/coilhq/web-monetization-projects/blob/main/packages/web-monetization-types/src/index.ts.

(And maybe leave the extension of `Document` to end-users)

**Comment by sublimator** [comment]
Hey, sorry @sidvishnoi 
Missed this! Will look into it.
You can look at these https://github.com/dacioromero/types-wm that @dacioromero maintains/publishes to check if they are suitable if/when you run out of patience here :)

**Comment by sidvishnoi** [comment]
Nice! Though, would be nicer if types get released from here as they will be in sync with the latest WM API.
Nothing urgent, but good to have :)

**Comment by sublimator** [comment]
@traviscrist 
We would need to register the the webmonetization namespace on npm huh?

**Comment by sharafian** [comment]
created a webmonetization org on npm; if we set up CI to do publishing I can generate keys for it
