### ISSUE TITLE
[Firefox] Firefox logging out from extension

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#2048]
> got signed out of my extension today. on the latest version (loaded as a temporary extension in FF). 

Could FF still be having problems with the /handler.html CSP ?
Unable to get token from coil.com on startup so the extension logs itself out ? 

Note, this could be happening on Chrome too, and the fact it was FF is irrelevant 

Investigate:
- [ ] Containers extension
- [ ] about:profiles usage
- [ ] "built in" containers ?
- [ ] Clearing cookies / site data upon exit

**Comment by sublimator** [comment]
Checked with MacOS Mozilla Firefox (89.0.1) and the background page is successfully getting the token via handler.html.

**Comment by sublimator** [comment]
![image](https://user-images.githubusercontent.com/525211/123401868-64259d80-d5d1-11eb-8a27-2b1e824cced1.png)

**Comment by natanlao** [comment]
I can reproduce this; Coil (just recently) requires sign-in whenever I quit Firefox. I'd prefer to not do this, since going through the auth flow every day / every other day can get a little tiresome.

* Coil 0.0.54
* Firefox 89.0.1 (64-bit)

**Comment by sublimator** [comment]
@natanlao 
Thanks very much for the data point!

**Comment by sublimator** [comment]
@natanlao 
If I'm able to publish a preview version of the extension, with some extra logging circa authentication, would you mind running it and sharing results ? I've personally not been able to reproduce this, despite a few reports from others.

Can you share what platform you're on ? 
How often do you quit Firefox ? You need to sign back in every time? Are you able to reproduce this consistently just by quitting ?

**Comment by natanlao** [comment]
>  If I'm able to publish a preview version of the extension, with some extra logging circa authentication, would you mind running it and sharing results ? I've personally not been able to reproduce this, despite a few reports from others.

Sure!

> Can you share what platform you're on ?

I'm running NixOS:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
```
>  How often do you quit Firefox ?

I don't quit Firefox manually, so once a day when I shut off my PC.

> You need to sign back in every time? Are you able to reproduce this consistently just by quitting ?

I just tested again, and, as you might expect, I wasn't able to reproduce :sweat_smile: I'm happy to run a preview version anyway in case I observe it again.

**Comment by sublimator** [comment]
@natanlao 
Thanks! Will get back to you :)

**Comment by natanlao** [comment]
After updating Firefox to 89.0.2, I'm now signed out of Coil again. It occurs to me that this might not happen on every quit, just when Firefox updates.

**Comment by sublimator** [comment]
Interesting!

**Comment by sublimator** [comment]
I downgraded to previous version of FF and upgraded (twice) but was unable to reproduce. 
Will keep you posted

**Comment by sublimator** [comment]
For the record, may be related to this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1313401

**Comment by sublimator** [comment]
@natanlao 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/525211/124688419-edf23680-df00-11eb-8a77-aaa7e5b420fe.png">

What is your setting here re: deleting cookies etc when FF is closed ?

**Comment by natanlao** [comment]
The "Delete cookies and site data when Firefox is closed" setting is also unchecked for me. I should mention here that I also use the Temporary Containers extension, but this logout behavior is relatively new, so I hadn't considered the extension to be a potential cause.

Thanks for looking into this!

**Comment by sublimator** [comment]
> I should mention here that I also use the Temporary Containers extension

https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

This one right ?

**Comment by natanlao** [comment]
That's the one!

**Comment by sublimator** [comment]
@natanlao 

There was a recent change where upon first launch of the extension, if you aren't logged into coil.com it will logout. This is to synchronize logging out with the site in the odd case when you log out when the extension is temporarily disabled. 

It maybe that you logged in using a temporary container which the extension can longer use upon restart and ...

**Comment by sublimator** [comment]
Will keep investigating anyway

**Comment by natanlao** [comment]
Ah, that makes sense -- there's a workaround to maintain persistence in select sites, so I'll try that out and report back. Thanks again!

**Comment by sublimator** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/525211/124714422-f2801480-df2b-11eb-97ad-0c542e712f24.png">

I'm unable to install it. Might have to try from source

**Comment by sublimator** [comment]
For the record, chatted to @cyberdees (another FF user) and he's not experienced this issue

**Comment by natanlao** [comment]
After some tinkering, I've found that if I'm logged out of the extension and I open coil.com in-browser, the extension will log itself in. That makes me think this issue might be related to containers after all...

**Comment by sublimator** [comment]
@natanlao 

To be %100 clear, you now think your particular issue is due to the containers extension?

**Comment by natanlao** [comment]
@sublimator Yes -- I did a little more testing today, and Coil works as intended if container-related addons are disabled.

For anyone finding this down the line using Coil with Temporary Containers and Multi-Account Containers, I followed [these steps](https://github.com/stoically/temporary-containers/wiki/Automatic-Mode#how-to-stay-logged-in-on-some-websites-in-automatic-mode) to stay logged into Coil in a container and click the Coil addon button when I start Firefox, which triggers the auth flow without having to reauthenticate.

**Comment by sublimator** [comment]
@natanlao  
Thanks for the update :)
Please let us know if you experience any other problems

**Comment by legowerewolf** [comment]
I'm getting this problem - Coil is logged out sometimes when I open Firefox. Haven't nailed down a pattern as to why, yet.

Firefox 97.0.2 on Windows 11 21H2 (build 22000.527). 
No container extensions installed. 
Extensions like Privacy Badger and Privacy Possum disabled for coil.com.

**Comment by legowerewolf** [comment]
Hm. So, got the same thing, with the extension showing it's logged out. Instead of clicking it, ending up on Coil.com, and getting logged in, I loaded it in devtools (about:debugging > inspect) and hit reload in the network tab, and it logged in. Checked by going to css-tricks.com, which I know is monetized, and it initialized correctly.

**Comment by legowerewolf** [comment]
I'm seeing this in the devtools logs, too, not sure if it's related. Only seeing it when the extension's not logged in.
```
Uncaught (in promise) Error: Expecting not null for sender.tab
    notNullOrUndef                   background.js:4146
    i                                background.js:4178
    pauseWebMonetization             background.js:2250
    handleMessage                    background.js:1911
    setRuntimeMessageListener        background.js:1753
```

Maybe see if a check on `sender` here would do anything?
https://github.com/coilhq/web-monetization-projects/blob/52437bfabd1cbf03a57a928f5777ee217d45221c/packages/coil-extension/src/background/services/BackgroundScript.ts#L918-L926

**Comment by sublimator** [comment]
@legowerewolf  
Thanks very much for diving in.
We've seen this sporadically and I've investigated it sporadically, even switching to use Firefox as my default browser for a time, but haven't been able to source the issue as yet. 

We actually inject in the background page an `<iframe>` with `src="https://coil.com"` so we then communicate with the content script running there. From memory, there is reason to believe it's not working consistently on Firefox. 

See here:
https://github.com/coilhq/web-monetization-projects/blob/b8e8919dd9791f6990e7f84a97f0dfeda6c1ba87/packages/coil-extension/src/background/services/AuthService.ts#L139-L142

If you are up to [building from source](https://github.com/coilhq/web-monetization-projects/blob/main/packages/coil-extension/docs/building-extension-for-designers.md) (doc for designers could prove useful if you have no prior orientation)
 you could swap out the `<iframe>` injection method with another (SiteToken#retrieve() => SiteToken#retrieveTabs(): 
https://github.com/coilhq/web-monetization-projects/blob/b8e8919dd9791f6990e7f84a97f0dfeda6c1ba87/packages/coil-extension/src/background/services/SiteToken.ts#L29-L49

Please note that you'll need to add the "tabs" permission to the manifest.json 

If you do, let me know how that goes for you. Otherwise, I'll take a further look into this issue again myself at some point. 

Thanks.

**Comment by sublimator** [comment]
> I'm seeing this in the devtools logs, too, not sure if it's related.

Interesting. I'm not sure if it's related either, but from memory that should be relatively harmless (not to say that it should be throwing that error in normal course) 

On a related note, actually, Firefox and Chrome had/have slightly different behavior related to the "tabs" permission. By giving `<all_urls>` permission on Chrome, a lot of the Tab object fields, which typically require "tabs" permission to access seem to be implicitly granted. We try to request the minimum amount of permissions. Perhaps this behavior has diverged (more?) ?

**Comment by legowerewolf** [comment]
Something to experiment with. I'm happy to try an experimental build if you think you might have a solution.

**Comment by sublimator** [comment]
@legowerewolf 
You mean you'd like me to publish an experimental build somewhere for you to install ? 
I can do that, but will be a few days

**Comment by sublimator** [comment]
@legowerewolf 
Will get on it. Thanks for your patience

**Comment by sublimator** [comment]
@legowerewolf 
Have submitted a build to the add-on store. Because it's a new publishing it will probably take a day or two. 
Will let you know

**Comment by sublimator** [comment]
@legowerewolf
Please try this out and let me know what you find, thanks:
https://addons.mozilla.org/en-GB/firefox/addon/coildev/

**Comment by legowerewolf** [comment]
Ok, so the dev version is working consistently. I am catching a flash of a Coil.com tab opening then being shut, but I haven't had it not log in once, and I open and close my browser several times a day. I don't keep windows open when I don't need them.

**Comment by legowerewolf** [comment]
Yeah, sounds good.

**Comment by sublimator** [comment]
@legowerewolf 
I updated the CoilDev extension. This time the only change is the extra `tabs` permission. 
Let me know how that goes for you. 
I suspect it's not going to work as well for you, but want to rule it out. 
Thanks

**Comment by legowerewolf** [comment]
Still seems like it's working fine, actually. Maybe give it another day or so before you tweak it to give it more time to show bugs, but I think it's working.

**Comment by sublimator** [comment]
@legowerewolf 
Yeah, let's see in some days!

**Comment by sublimator** [comment]
@legowerewolf 
What's the verdict? What's your confidence that the bug is fixed simply by adding the "tabs" permission ?

**Comment by sublimator** [comment]
@legowerewolf 
Still good ?

**Comment by legowerewolf** [comment]
Yeah, seems like it.
