### ISSUE TITLE
Extension state does not reflect coil.com account state

### ISSUE THREAD

**Issue by traviscrist** [coilhq/web-monetization-projects#21]
The extension's state does not reflect the state of the users subscription on coil.com

1. When your subscription expires the extension keeps trying to pay and shows "Coil is Paying" with no moving green dots. The jwt token is invalid and the error 
```
lp-plugin-btp:error error authenticating btp connection +3s {"code":"F00","name":"NotAcceptedError","triggeredAt":"2019-11-01T15:18:48.071Z","data":"auth token must include throughput","protocolData":[]}
```
The extension in this state should change to telling the user they need to subscribe
If you log out and back into coil.com this is fixed. 

2. Once you subscribe the extension stays in the you need to subscribe state. Once I subscribe on coil.com the extension should immediately let me start using my subscription. To fix this I had to log out and back into coil.com.

**Comment by sublimator** [comment]
@traviscrist 
This should be fixed in 0.0.40
