### ISSUE TITLE
Extension regression when used with wordpress plugin

### ISSUE THREAD

**Issue by matdehaast** [coilhq/web-monetization-projects#2144]
It appears there seems to be a regression with the extension when used with the Wordpress Plugin.

The extension seems to be throwing an error. Below is the extension error and also a video of the issue occuring

![image](https://user-images.githubusercontent.com/12172996/126127636-83388cda-b5a0-4c9b-95f0-baba409e9341.png)

https://user-images.githubusercontent.com/12172996/126127921-3575ffd4-bfe4-4bc1-ab0e-56af845bf0e9.mp4

@SarahCoilAccount is going to post the details to setup a local environment to setup wordpress locally to debug.

**Comment by SarahCoilAccount** [comment]
On Friday an error arose with the WordPress plugin.

This error is only applicable to Coil members who are signed in and using the extension. 

- Partially gated content is when only certain paragraphs have been gated to be visible only to Coil members. When viewing partially gated content as a Coil member the gating message appears 'normally' (it shouldn't be there at all). But after a few moments it appears abnormally and takes up more of the screen than it should. It should not appear at all.
- Fully gated content is when an entire post is only visible to Coil members. When viewing fully gated content as a Coil member the gating message does not appear but neither does any of the content. 
- The pending monetization state seems to be lasting longer than it used to.
- This error has not popped up before and is problematic across previous versions of the plugin as well as the current version which was just released. 

Everything seems to be working as expected for users who have not got the extension installed or do not have an active Coil account, and therefore see the gated messages as usual.

**Comment by sublimator** [comment]
Can reproduce on this page:
https://gftwdev.wpengine.com/ 

There seems to be TWO monetization tags ( 1 meta AND 1 link ) 
![image](https://user-images.githubusercontent.com/525211/126139129-3ba7ab1c-b24b-4e00-9f88-d08b14a8db44.png)

Would seem to indicate this change from June:
https://github.com/coilhq/web-monetization-projects/commit/fe47af13f0dd0303c31d7977df0c2cf06ebff2e8

**Comment by sublimator** [comment]
Can confirm this bug did not exist in 0.0.52

**Comment by sublimator** [comment]
Was introduced with this:
https://github.com/coilhq/web-monetization-projects/pull/1964

**Comment by sublimator** [comment]
This was actually introduced here:
https://github.com/coilhq/web-monetization-projects/pull/2070
