### ISSUE TITLE
Detect if multiple extensions are activated and warn of undefined behavior 

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#2613]
With people playing with multiple extensions (CoilDev, Coil, CoilPreview) things could get puzzling

**Comment by Danisco212** [comment]
- [x] send message from one extension to another in chrome
- [x] send message from one extension to another in firefox
- [x] open chrome://extensions from secondary extension when in chrome
- [ ] open about:debugging from secondary extension when in firefox

**Comment by sublimator** [comment]
#2910

**Comment by sublimator** [comment]
Closed in #2910
