### ISSUE TITLE
crx-hotreload does not work with MV3

### ISSUE THREAD

**Issue by Danisco212** [coilhq/web-monetization-projects#2742]
Each resolution and its issues (accordingly)

code from: https://github.com/xpl/crx-hotreload/blob/master/hot-reload.js

Steps
1. Copied code to service-worker
2. Copied code into content script
3. Added code to injection script
4. Tried passing chrome.management from service worker to content script

Issues
1. chrome.runtime.getPackageDirectoryEntry error when code is in background script (service_worker)
2. chrome.management is undefined in content-script thus chrome.runtime.getSelf can’t be executed
3. In injection script, same issue ‘chrome.management’
4. Doesn’t recognize getSelf property(function) in chrome.management

**Comment by sublimator** [comment]
Worked around by adding a webpack plugin with a websocket server
