### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#301]
- [x] Go through release checklist (see [issue](https://github.com/coilhq/web-monetization-projects/issues/305))
- [x] Add to package.json/build scripts etc 
- [x] Go through [docs](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/)
- [x] [Publish](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension)
  - [x] Go through with CoilDev "draft" but don't publish
  - [x] Publish "Coil" extension
     - [x] Need [300x300 png logo](https://drive.google.com/open?id=1Sl0Yr4LbegvI01UGOdRXiEEUS0H3ZNmx)
     - [x] Need 440x280 promotional tile
- [x] Await Review

**Comment by fruehle** [comment]
@sublimator I didn't find specs for where the promotional tile would go, so I just did the logo as a best guess. Will you add screenshots to it once it's uploaded?

![coil-edge-extension](https://user-images.githubusercontent.com/19295116/72926002-847c6900-3d08-11ea-828d-566a4dccd285.png)
![coil-edge-promotional-tile](https://user-images.githubusercontent.com/19295116/72926003-847c6900-3d08-11ea-9c32-f918e5e763ca.png)

**Comment by sharafian** [comment]
kicked off submission process, waiting on review and also waiting on account verification

**Comment by sublimator** [comment]
Published:
https://microsoftedge.microsoft.com/addons/detail/ljionajlbinlfkdnpkloejeoogfgkojm?hl=en-US
