### ISSUE TITLE
Web Extension ocasionally throws "Error in event handler: Error: expecting state transition"

### ISSUE THREAD

**Issue by AlexLakatos** [coilhq/web-monetization-projects#3103]
From Slack:

[Randy Lubin](https://app.slack.com/team/U02UWD4R69Y)
  [7:40 PM](https://interledger.slack.com/archives/CNYTXJKMX/p1655577648006799)
Not sure if this is the right place to ask (lmk if not) but I’m occasionally getting a console error with my web monetization enabled site:
```
Error in event handler: Error: expecting state transition
    at c.dispatchMonetizationStartEventAndSetMonetizationState (chrome-extension://locbifcbeldmnphbgkdigjmkbfkhbnca/content.js:2:527260)
    at chrome-extension://locbifcbeldmnphbgkdigjmkbfkhbnca/content.js:2:491513
```

This occurs with the Coil extension running on Chrome and I have the following code on my site:

```
document.monetization?.addEventListener('monetizationstart', () => {
        this.monetizationStarted()
      })
```
I’ll add that despite the error message in console, everything appears to be working correctly. Any thoughts?

**Comment by sublimator** [comment]
Thanks.
Is it just on one particular site?

**Comment by randylubin** [comment]
Happy to answer any follow-up questions and share more code if relevant. As I mentioned, everything seems to be working just fine, other than that error popping up.

I have both the <meta> and <link> monetization approaches on the page

**Comment by sublimator** [comment]
@randylubin 

 > I have both the and monetization approaches on the page
Sorry, can you clarify ?

Can you give more details:
* The payment pointer used (if you don't mind divulging) 
* A link to the page (or code excerpt) 
* What OS ?
* What browser (and version) ?

**Comment by randylubin** [comment]
@sublimator here you go:

- Payment pointer: $ilp.uphold.com/WMbkRBiZFgbx
- Link to a page where I get the error (though there are many other pages, too): [Shuffled Demo](https://storysynth.org/Shuffled/1N5eeyKTVWo5QeGcUV_zYtwtR0DikJCcvcj6w69UkC1w/)
- MacOS 12.4
- Chrome Version 103.0.5060.114 (Official Build) (arm64)

The page has two monetization approaches:

- Meta: `<meta data-vue-meta="1" name="monetization" content="$ilp.uphold.com/WMbkRBiZFgbx" data-vmid="monetization">`
- Link: <link data-v-4411ba56="" rel="monetization" onmonetization="console.log('monetization event triggered')" href="$ilp.uphold.com/WMbkRBiZFgbx">

And then there's the code I pasted earlier:
`document.monetization?.addEventListener('monetizationstart', () => {
        this.monetizationStarted()
      })`

**Comment by sublimator** [comment]
Great, thanks! 
I have an idea of what it might be.

You built the extension yourself ? 
What version are you using, that you're trying onmonetization 
?

**Comment by randylubin** [comment]
I built the Story Synth web app (the linked page) but the extension is just the public version of the Chrome Coil extension (v0.0.59). At one point I was playing around with the dev build which looks for `link` instead of `meta` but that's currently uninstalled.

**Comment by sublimator** [comment]
Thanks

**Comment by sublimator** [comment]
@randylubin 
https://chrome.google.com/webstore/detail/coildev/hcohoecolgmlofifjaobjhidpoaciknp

Sorry, have been occupied elsewhere. 
Can you let me know if that sorts your problem? 

Thanks :)

**Comment by randylubin** [comment]
Hmm for some reason my reply didn't show up earlier:

Yup - that fixes it for me. Thanks!

**Comment by sublimator** [comment]
Yeah, it rang a bell. I did a lot of the WM2 work last year around xmas, and that bug sounded familiar. I thought I fixed it in the WM2 branch.

**Comment by randylubin** [comment]
Yup - that fixes it for me. Thanks!
