### ISSUE TITLE
coil-extension: Content Security Policy of your site blocks the use of 'eval' in JavaScript

### ISSUE THREAD

**Issue by tomayac** [coilhq/web-monetization-projects#3538]
I noticed that the extension (version 0.0.63) stopped working. Go to https://codepen.io/, which uses the correct markup:

<img width="1211" alt="Screenshot 2022-12-21 at 15 34 32" src="https://user-images.githubusercontent.com/145676/208878375-920fe294-b267-4a78-94d0-d20f49810663.png">

You will notice that the extension shows the red dot:

<img width="35" alt="Screenshot 2022-12-21 at 15 34 50" src="https://user-images.githubusercontent.com/145676/208878427-280fe44c-8b41-4fec-8390-830a8aeea7ce.png">

Inspecting `background.js`, I noticed an issue "Content Security Policy of your site blocks the use of 'eval' in JavaScript".  

<img width="1149" alt="Screenshot 2022-12-21 at 15 35 26" src="https://user-images.githubusercontent.com/145676/208878588-3c00a969-59d3-4402-b4ab-22970774c099.png">

It's this block that causes the error:

```js
 try {
  return Function("return function*() {}")()
} catch (e) {}
```

**Comment by sublimator** [comment]
What browser are you using?

**Comment by sublimator** [comment]
@tomayac 

Hi, are you using Chrome or Firefox?

**Comment by tomayac** [comment]
Sorry, was OoO. I'm using Chrome.

**Comment by sublimator** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/525211/214759715-4e29b504-0941-4611-8b23-4c1a4e8477de.png)

Curiously, at a glance, the extension seems to be working (the popup showed stream). I typically have a development build enabled, so not sure about the published version which I only checked quickly. 

I checked the CSP Violations tab with the local development build ( no minification ):

![image](https://user-images.githubusercontent.com/525211/214760966-52e240df-f080-4ed3-8cc1-7c68b05cdac1.png)

The relevant code is from the is-generator-function module:
```
  !*** ../../../../.yarn/berry/cache/is-generator-function-npm-1.0.7-f264e5a57d-9.zip/node_modules/is-generator-function/index.js ***!
  \**********************************************************************************************************************************/
/***/ ((module) => {

"use strict";


var toStr = Object.prototype.toString;
var fnToStr = Function.prototype.toString;
var isFnRegex = /^\s*(?:function)?\*/;
var hasToStringTag = typeof Symbol === 'function' && typeof Symbol.toStringTag === 'symbol';
var getProto = Object.getPrototypeOf;
var getGeneratorFunc = function () { // eslint-disable-line consistent-return
	if (!hasToStringTag) {
		return false;
	}
	try {
		return Function('return function*() {}')();
	} catch (e) {
	}
```

The error is caught and ignored, so that explains why the extension was still working for me. 

@tomayac 

Perhaps you happened upon this issue while there was some kind of service outage at Coil or one of the wallets (uphold, judging by your screenshots) ?

**Comment by sublimator** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/525211/214762073-17cd7e88-632f-4497-b092-622f331655e5.png">

That generally means you aren't logged in. When the popup button is in that state, clicking on it the action button will route you to login.

**Comment by sublimator** [comment]
Related: https://github.com/coilhq/web-monetization-projects/issues/2685

**Comment by tomayac** [comment]
I permanently have the red dot, and when I click the icon, I land straight in my logged in area on https://coil.com/settings/account:
 
<img width="661" alt="Screenshot 2023-01-27 at 12 33 50" src="https://user-images.githubusercontent.com/145676/215076706-f1629f70-b3db-40d8-afad-7fd6ea11877d.png">

**Comment by sublimator** [comment]
That page is where login redirects you to if you are already logged in. 
It means the extension isn't getting the auth token for some reason. 
I will send you some debugging steps tomorrow as it's late here now

**Comment by tomayac** [comment]
Thank you! `<3`

**Comment by sublimator** [comment]
Sorry, I owed you some debugging steps, and I got distracted by other work after the weekend. 
In the meantime you could try simply toggling the extension and logging back in and out of Coil.

**Comment by tomayac** [comment]
Hmm, interesting. Logging out and in again seems to have worked. It's now green again on supporting sites. Funny that the site still thought I was logged in.

**Comment by sublimator** [comment]
The authentication must have gotten out of sync somehow. I haven't heard of it happening in a very long time, but it is of course possible. It's a pity I didn't get you some steps to see what state your token was in, however we are moving to a new auth system, using cookies, so will focus efforts there.

**Comment by tomayac** [comment]
Thanks anyway. Closing as resolved. ♥️
