### ISSUE TITLE
Renovate not working 

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#3558]
- It seems to be creating branches but no opening the PRs 
- Everything seems to be very slow with lags at cloning steps

Trying specifying version 34.83.1 on the `npx renovate ...` command line

**Comment by sublimator** [comment]
> DEBUG: Pull request creation error (repository=coilhq/web-monetization-projects, branch=sublimate/addons-linter-5.x)
       "err": {
         "message": "repository-changed",
         "stack": "Error: repository-changed\n    at handleGotError (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/util/http/github.ts:139:14)\n    at GithubHttp.request (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/util/http/github.ts:353:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at GithubHttp.requestJson (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/util/http/index.ts:256:17)\n    at Proxy.createPr (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/modules/platform/github/index.ts:1501:5)\n    at ensurePr (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/repository/update/pr/index.ts:356:14)\n    at processBranch (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/repository/update/branch/index.ts:686:28)\n    at writeUpdates (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/repository/process/write.ts:159:17)\n    at update (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/repository/process/extract-update.ts:169:11)\n    at Object.renovateRepository (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/repository/index.ts:65:19)\n    at attributes.repository (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/global/index.ts:181:11)\n    at start (/Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/workers/global/index.ts:166:7)\n    at /Users/nicholasdudfield/.npm/_npx/f8a499a3177c938e/node_modules/renovate/lib/renovate.ts:18:22"
       }

**Comment by sublimator** [comment]
```
         "response": {
           "statusCode": 422,
           "statusMessage": "Unprocessable Entity",
           "body": {
             "message": "For same-org, cross-repo pulls, 'head_repo' is required",
             "errors": [
               {"resource": "PullRequest", "field": "head", "code": "invalid"}
             ],
             "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
           },
           "headers": {
```

**Comment by peter-evans** [comment]
@sublimator I think this is the same issue that many users experienced here: https://github.com/peter-evans/create-pull-request/issues/1459

GitHub made a fix and it should be resolved now.

(I found this while searching GitHub for related issues.)

**Comment by sublimator** [comment]
@peter-evans 
Very kind of you! Thanks for taking the time to point it out
