### ISSUE TITLE
Update Extension Copy (Part II) - Based on Site URL

### ISSUE THREAD

**Issue by fruehle** [coilhq/web-monetization-projects#385]
More updates on the extension.

When the extension is paying, please remove the string "Coil is paying the creator."
but keep it for Youtube and Twitch addresses.

**Comment by sublimator** [comment]
![image](https://user-images.githubusercontent.com/525211/74495225-bfd61600-4f09-11ea-9d74-269f643c2064.png)

So basically like this ?

**Comment by fruehle** [comment]
Yes exactly :)
