### ISSUE TITLE
Don't retry on some SPSP errors

### ISSUE THREAD

**Issue by sharafian** [coilhq/web-monetization-projects#40]
Right now any SPSP query on a web monetized site gets retried infinitely if it fails. We might want to change it so that certain error codes on the SPSP server will not trigger a retry. I'm thinking that 500s should retry but any other error should just stop the monetization process. If you got a 401 for instance there's little reason to retry the SPSP query; it'll just be wasting network usage.

**Comment by sublimator** [comment]
Added a fix for this with #48 . Still need to add a some kind of test, puppeteer or otherwise.
