### ISSUE TITLE
Use updated ilp-protocol-stream exchange rate param to avoid packet volley

### ISSUE THREAD

**Issue by traviscrist** [coilhq/web-monetization-projects#53]
In the current version of the extension I believe it is using the ilp-protocol-streams packet volley to determine the exchange rate before sending payments. This leads to a long time to send first real packet time. It takes 3-5 test packets to find an appropriate exchange rate. 

https://github.com/interledgerjs/ilp-protocol-stream/pull/119

We should be able to set the exchange rate since we don't care and then stream will just start sending packets immediately rather than figuring out what the exchange rate is that the connection can handle.

If you look at the logs you can see the volley as test packets that are in 10^x amounts: https://github.com/interledgerjs/ilp-protocol-stream/blob/762d4b36583ab70848b0f6d7fe69a4ac3d884644/src/connection.ts#L1178-L1231

**Comment by sublimator** [comment]
Talked to Travis. The trick would be to use exchangeRate = 1 and slippage 1

**Comment by traviscrist** [comment]
@sublimator try that out, we might have to use the actual exchange rate here though. Lets try out what I mentioned though, bc if it works thats ideal.

**Comment by sublimator** [comment]
@traviscrist 
Tried it and the difference is not really noticeable to the human eye. 

@sharafian said:
```
there's a timer loop that updates the amount every 2s
we could make the first one quicker
```
I believe, but am not sure, he's talking about the server/connector side.

**Comment by traviscrist** [comment]
> @traviscrist
> Tried it and the difference is not really noticeable to the human eye.

If you compare the before and after though there are about 3 - 5 round trips to establish a connection and start sending money. With this is should be immediate. Idk if the human eye can notice it but you can see it in the logs and should be able to use the chrome dev tools to see if there is a difference in the time till money is sent.

**Comment by sublimator** [comment]
> Tried it and the difference is not really noticeable to the human eye.

I didn't mean that to say it's not worth doing, only that I don't think it's the biggest factor.
I just tried it really quickly today while fixing an issue @sharafian provide a nice event logging repro for. It made it really easy to see time-to-monetization

**Comment by traviscrist** [comment]
> > Tried it and the difference is not really noticeable to the human eye.
> 
> I didn't mean that to say it's not worth doing, only that I don't think it's the biggest factor.

That makes sense, I wonder what it could be then since you have the web crypto and that in. Interesting...

> I just tried it really quickly today while fixing an issue @sharafian provide a nice event logging repro for. It made it really easy to see time-to-monetization

Cool, does it show results? It would be really cool to get that into ci somehow so on each build you could see if things improved or got worse
