### ISSUE TITLE
Only Pay while stream?

### ISSUE THREAD

**Issue by SamuelEVicente** [coilhq/web-monetization-projects#590]
I hope this is the correct place to post this question. At Musicoin we offer users to stream music and pay the content creator immediately with smart contracts. We are looking into web monetization, we are wondering whether it’s possible to only make the user pay while streaming?

**Comment by matdehaast** [comment]
Hi @SamuelEVicente .

That is possible by dynamically inserting/removing the creators Payment Pointer only when the user is actually streaming the music. There is actually an example of this https://gfdgvrj.dlvr.cloud/. Though that example pays the platform when music is not being streamed. But that could easily be changed to no payments at all.

**Comment by sublimator** [comment]
> I hope this is the correct place to post this question.
It's fine, but you'll get more eyeballs beyond code monkeys @ this repo, where the spec is developed:
https://github.com/interledger/webmonetization.org

**Comment by SamuelEVicente** [comment]
@matdehaast Awesome, thank you for the reference.
