### ISSUE TITLE
Check privacy-pass hash to point method

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#639]
We are currently using the deprecated one, should we switch ?
https://github.com/privacypass/challenge-bypass-extension/blob/master/src/ext/config.js#L114-L117

```typescript
/**
 * DEPRECATED: Method for hashing to curve based on the principal of attempting
 * to hash the bytes multiple times and recover a curve point. Has non-negligble
 * probailistic failure conditions.
 * @param {sjcl.bitArray} seed
 * @param {sjcl.hash} hash hash function for hashing bytes to base field
 * @param {sjcl.bitArray} label
 * @return {sjcl.ecc.point} returns a curve point on the active curve
 */
function hashAndInc(
  seed: sjcl.BitArray,
  hash: sjcl.SjclHashStatic,
  label: SjclHashable
```

**Comment by sublimator** [comment]
https://github.com/privacypass/challenge-bypass-extension/blob/master/docs/HASH_TO_CURVE.md#hash-and-increment

**Comment by sharafian** [comment]
This would have to be coordinated with the backend, I'm not sure if the challenge bypass server supports that new version. The main reason to switch appears to be that there's no probabilistic failure condition where you need to hash some unknown number of times. As it's mostly just a matter of performance I'm comfortable keeping hash and inc for now.

**Comment by sublimator** [comment]
Yeah, I don't think it's an issue really now that I understand what it's doing. I just made a note of it
