### ISSUE TITLE
Firefox shows "This site is not monetized" in private windows

### ISSUE THREAD

**Issue by traviscrist** [coilhq/web-monetization-projects#715]
I noticed that when browsing in private mode on firefox, with the coil extension installed but not logged in, the extension will incorrectly say "This site is not Web-Monetized" for _any_ site. Even web monitized sites like cinnamon. 

It also seems to do this when you are logged in.

**Comment by sublimator** [comment]
Will look into it, but it's likely the "private" mode being truly private and the content script not having privileged access to the page.

**Comment by sublimator** [comment]
https://www.ghacks.net/2019/02/01/firefox-will-soon-disallow-extensions-in-private-mode-by-default/

**Comment by sublimator** [comment]
![image](https://user-images.githubusercontent.com/525211/84240283-ffafb180-ab27-11ea-9a59-7267f07ed88c.png)
