### ISSUE TITLE
Update Extension Descriptions in stores to mention open source

### ISSUE THREAD

**Issue by traviscrist** [coilhq/web-monetization-projects#729]
The descriptions for the Coil extension listings in Chrome, Microsoft, Firefox, etc. web stores should mention that the extension is open-source and the source code is available at https://github.com/coilhq/web-monetization-projects/tree/master/packages/coil-extension

**Comment by sharafian** [comment]
This appears to be tied to publishing in the Chrome Webstore. Let's remember to close this out once we update the description on the next release

**Comment by sublimator** [comment]
- [x] https://chrome.google.com/webstore/detail/coil/locbifcbeldmnphbgkdigjmkbfkhbnca?hl=en
- [x] https://microsoftedge.microsoft.com/addons/detail/coil/ljionajlbinlfkdnpkloejeoogfgkojm
- [x] https://addons.mozilla.org/en-US/firefox/addon/coil/

Looks all sorted!
