### ISSUE TITLE
Payments happening in backgrounded tabs

### ISSUE THREAD

**Issue by traviscrist** [coilhq/web-monetization-projects#735]
A user has reported that when using the https://addons.mozilla.org/en-US/firefox/addon/paytrackr/ extension it shows payments occurring in backgrounded tabs.

When the user exports the CSV from PayTracker they see payments made when tabs were backgrounded and they were sleeping. 

We should double check that the extension is not paying in backgrounded tabs as this user has observed. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://coil.frontapp.com/open/top_2tpu7)

**Comment by sublimator** [comment]
> When the user exports the CSV from PayTracker they see payments made when tabs were backgrounded and they were sleeping.

You CAN have multiple tabs streaming at once IF they are in different windows

**Comment by traviscrist** [comment]
@sublimator backgrounded tabs though, shouldn't only tabs that the user can see be the ones streaming payments?

**Comment by sublimator** [comment]
As mentioned on slack, yes, backgrounded tabs shouldn't have active streams. 
I did do a manual test for this. 
Perhaps the paytrackr extension is doing something weird ?

I believe it's developed open source, so I will open an issue there and see if the author has any clues.

**Comment by sorxrob** [comment]
Hi everyone. Thanks for the report. I'll be checking this one. For the meantime if the issue persists, just restart the browser.

Sorry for the inconvenience.

**Comment by sublimator** [comment]
Thanks @sorxrob !

**Comment by sublimator** [comment]
https://github.com/sorxrob/paytrackr/issues/4#issuecomment-674344952
