### ISSUE TITLE
Update popup copy 

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#74]
https://github.com/coilhq/coil/issues/2858

**Comment by traviscrist** [comment]
@sublimator can you complete this next week to align with our updated settings release? Thanks!

**Comment by sublimator** [comment]
@traviscrist 
Sure

@fruehle 
Hi, I'm not entirely sure as to the changes required.
Could you give me a list ?
Thanks!

**Comment by fruehle** [comment]
@travis: could you remind me what that ticket was. I want to give nick directions, but I’m also a bit lost which pop up is meant.

Cheers,
Fabs

**Comment by sublimator** [comment]
@fruehle 
If you haven't, check: https://github.com/coilhq/coil/issues/2858

**Comment by fruehle** [comment]
Thanks got it.
So it’s just a copy change. We changed the naming from subscription to membership and site to content.

The screenshot in the ticket shows the updated copy.  There might be other copy in the extension that uses subscription. I’m on my phone right now so I don’t know from the top of my head if that’s the case.

Hope that helps.
Cheers,
Fabs

**Comment by sublimator** [comment]
Great, thanks the quick response!
