### ISSUE TITLE
Implement <link> tag

### ISSUE THREAD

**Issue by sharafian** [coilhq/web-monetization-projects#746]
We'll likely need to modify the web monetization spec before we merge this.

As has been brought up and discussed https://github.com/WICG/webmonetization/issues/19 there are several reasons to switch to a link tag instead of a meta tag.

I'd propose that we add support for a link rel=monetization which behaves the same as the meta tag. We shouldn't deprecate the meta tag just yet until we have a strong reason to.

If the link rel=monetization is present alongside a meta name=monetization then the link tag should override the meta tag. This gives people an upgrade path.

Also in keeping with the semantics of link tags, the href param including the payment pointer should only be expressed in URL-form, not in payment-pointer form (i.e. use https://wallet.example/alice instead of $wallet.example/alice)

**Comment by sublimator** [comment]
Implemented in #784
