### ISSUE TITLE
Coil extension readme followup

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#799]
> If you aren’t signed in to your Coil account, the extension still checks each page for the meta tag, but does not inject the Web Monetization API nor stream payments from Coil.

This is not technically true. 
It actually always injects the document.monetization object when the extension is installed. 

> Development workflow
> For quick iterating, see the repo root readme section for info on speeding up webpack by skipping type checking.

This link is stale

**Comment by sharafian** [comment]
Good catches, can you update the README to reflect those?
