### ISSUE TITLE
CI for pull requests from forks

### ISSUE THREAD

**Issue by sublimator** [coilhq/web-monetization-projects#85]
The environment variables in the CI are only available for branches on the main repo. This means that some tests fail as they are looking for COIL_USER/COIL_PASSWORD

**Comment by sublimator** [comment]
Apparently we could use restricted contexts and add a step that requires approval to the workflow. If not the exact step itself, then another doing essentially the same thing, could be ran in the case of branches pushed to this main repo. 

See: https://circleci.com/docs/2.0/contexts/

**Comment by traviscrist** [comment]
@sublimator is this just for the extension ci jobs?

**Comment by sublimator** [comment]
extension/oauth-scripts yeah
